const db = require("../db");
const { Trader } = require("../models");

db.on("error", console.error.bind(console, "MongoDB connection error:"));

const main = async () => {
  const traders = [
    {
      name: `Prapor`,
      image: `https://assets.tarkov.dev/54cb50c76803fa8b248b4571.webp`,
      quests: [
        `Debut`,
        `Checking`,
        `Shootout Picnic`,
        `Search Mission`,
        `Delivery from the Past`,
        `BP Depot`,
        `Bad Rep Evidence`,
        `Ice Cream Cones`,
        `The Bunker - Part 1`,
        `Postman Pat - Part 1`,
        `Polikhim Hobo`,
        `You've Got Mail`,
        `The Bunker - Part 2`,
        `Big Customer`,
        `No Offence`,
        `No Place for Renegades`,
        `Documents`,
        `Shaking up the Teller`,
        `Glory to CPSU`,
        `The Punisher - Part 1`,
        `The Punisher - Part 2`,
        `The Punisher - Part 3`,
        `The Punisher - Part 4`,
        `The Punisher - Part 5`,
        `The Punisher - Part 6`,
        `Reconnaissance`,
        `Easy Job - Part 1`,
        `Easy Job - Part 2`,
        `Green Corridor`,
        `Grenadier`,
        `Insomnia`,
        `Our Own Land`,
        `Anesthesia`,
        `Kings of the Rooftops`,
        `Regulated Materials`,
        `Best Job in the World`,
        `Test Drive - Part 1`,
        `Test Drive - Part 2`,
        `Perfect Mediator`,
        `Capturing Outposts`,
        `Intimidator`,
        `Escort`,
      ],
    },
    {
      name: `Therapist`,
      image: `https://assets.tarkov.dev/54cb57776803fa99248b456e.webp`,
      quests: [
        `Shortage`,
        `Operation Aquarius - Part 1`,
        `Operation Aquarius - Part 2`,
        `Painkiller`,
        `Sanitary Standards - Part 2`,
        `Pharmacist`,
        `Drug Trafficking`,
        `Lost Contact`,
        `General Wares`,
        `Postman Pat - Part 2`,
        `Car Repair`,
        `Health Care Privacy - Part 1`,
        `Health Care Privacy - Part 2`,
        `Health Care Privacy - Part 3`,
        `An Apple a Day Keeps the Doctor Away`,
        `Health Care Privacy - Part 4`,
        `Health Care Privacy - Part 5`,
        `Hippocratic Oath`,
        `Out of Curiosity`,
        `Trust Regain`,
        `Population Census`,
        `Supply Plans`,
        `Disease History`,
        `Dangerous Road`,
        `Urban Medicine`,
        `Seaside Vacation`,
        `Colleagues - Part 1`,
        `Colleagues - Part 2`,
        `Colleagues - Part 3`,
        `Athlete`,
        `Private Clinic`,
        `Decontamination Service`,
        `Crisis`,
      ],
    },
    {
      name: `Fence`,
      image: `https://assets.tarkov.dev/579dc571d53a0658a154fbec.webp`,
      quests: [`The Choice`],
    },
    {
      name: `Skier`,
      image: `https://assets.tarkov.dev/58330581ace78e27b8b10cee.webp`,
      quests: [
        `Supplier`,
        `The Extortionist`,
        `Stirrup`,
        `What is on the Flash Drive?`,
        `Golden Swag`,
        `Friend from the West - Part 1`,
        `Friend from the West - Part 2`,
        `Chemical - Part 1`,
        `Chemical - Part 2`,
        `Chemical - Part 3`,
        `Chemical - Part 4`,
        `Loyalty Buyout`,
        `Kind of Sabotage`,
        `Safe Corridor`,
        `Long Road`,
        `Missing Cargo`,
        `Rigged Game`,
        `Vitamins - Part 1`,
        `Vitamins - Part 2`,
        `Informed Means Armed`,
        `Hint`,
        `Lend-Lease - Part 1`,
        `Lend-Lease - Part 2`,
        `Chumming`,
        `Silent Caliber`,
        `Bullshit`,
        `Setup`,
        `Debtor`,
        `House Arrest - Part 1`,
        `House Arrest - Part 2`,
        `Flint`,
        `Top Secret`,
        `Night Sweep`,
      ],
    },
    {
      name: `Peacekeeper`,
      image: `https://assets.tarkov.dev/5935c25fb3acc3127c3d8cd9.webp`,
      quests: [
        `Fishing Gear`,
        `Tigr Safari`, 
        `Scrap Metal`, 
        `Eagle Eye`,
        `Humanitarian Supplies`,
        `The Cult - Part 2`,
        `Spa Tour - Part 1`,
        `Spa Tour - Part 2`,
        `Spa Tour - Part 3`,
        `Spa Tour - Part 4`,
        `Spa Tour - Part 5`,
        `Spa Tour - Part 6`,
        `Spa Tour - Part 7`,
        `Cargo X - Part 1`,
        `Cargo X - Part 2`,
        `Cargo X - Part 3`,
        `Cargo X - Part 4`,
        `Overpopulation`,
        `Counteraction`,
        `The Cult - Part 1`,
        `Wet Job - Part 1`,
        `Wet Job - Part 2`,
        `Wet Job - Part 3`,
        `Wet Job - Part 4`,
        `Wet Job - Part 5`,
        `Wet Job - Part 6`,
        `Mentor`,
        `Classified Technologies`,
        `Revision - Lighthouse`,
        `Revision - Reserve`,
        `Revision - Streets of Tarkov`,
        `Road Closed`,
        `Samples`,
        `TerraGroup Employee`,
        `Worst Job in the World`,
        `Peacekeeping Mission`,
        `Your Car Needs a Service`,
        `The Guide`,
        `The Cleaner`,
        `Trophies`,
        `Special Equipment`,
        ],
    },
    {
      name: `Mechanic`,
      image: `https://assets.tarkov.dev/5a7c2eca46aef81a7ca2145d.webp`,
      quests: [
        `Introduction`,
        `Gunsmith - Part 1`,
        `Gunsmith - Part 2`,
        `Gunsmith - Part 3`,
        `Gunsmith - Part 4`,
        `Gunsmith - Part 5`,
        `Gunsmith - Part 6`,
        `Gunsmith - Part 7`,
        `Gunsmith - Part 8`,
        `Gunsmith - Part 9`,
        `Gunsmith - Part 10`,
        `Gunsmith - Part 11`,
        `Gunsmith - Part 12`,
        `Gunsmith - Part 13`,
        `Gunsmith - Part 14`,
        `Gunsmith - Part 15`,
        `Gunsmith - Part 16`,
        `Gunsmith - Part 17`,
        `Gunsmith - Part 18`,
        `Gunsmith - Part 19`,
        `Gunsmith - Part 20`,
        `Gunsmith - Part 21`,
        `Gunsmith - Part 22`,
        `Farming - Part 1`,
        `Farming - Part 3`,
        `Farming - Part 4`,
        `Signal - Part 1`,
        `Scout`,
        `Farming - Part 2`,
        `Signal - Part 2`,
        `Signal - Part 3`,
        `Signal - Part 4`,
        `Bad Habit`,
        `Broadcast - Part 1`,
        `Broadcast - Part 2`,
        `Insider`,
        `Back Door`,
        `A Shooter Born in Heaven`,
        `Surplus Goods`,
        `Corporate Secrets`,
        `Watching You`,
        `Chemistry Closet`,
        `Energy Crisis`,
        `Surveillance`,
        `Fertilizers`,
        `Import`,
        `Psycho Sniper`,
        `Network Provider - Part 1`,
        `Network Provider - Part 2`,
        `Assessment - Part 1`,
        `Assessment - Part 2`,
        `Assessment - Part 3`,
        `Key to the Tower`,
        `Knock-Knock`,
        `Getting Acquainted`,
        `Calibration`,
        `The Courier`,
      ],
    },
    {
      name: `Ragman`,
      image: `https://assets.tarkov.dev/5ac3b934156ae10c4430e83c.webp`,
      quests: [
      `Only Business`,
      `Make ULTRA Great Again`,
      `Big Sale`,
      `Audit`,
      `Dressed to Kill`,
      `Database - Part 1`,
      `Database - Part 2`,
      `A Fuel Matter`,
      `Inventory Check`,
      `Gratitude`,
      `The Blood of War - Part 1`,
      `Ballet Lover`,
      `Minibus`,
      `Sew it Good - Part 1`,
      `Sew it Good - Part 2`,
      `Sew it Good - Part 3`,
      `Sew it Good - Part 4`,
      `Charisma Brings Success`,
      `The Blood of War - Part 2`,
      `Audiophile`,
      `The Key to Success`,
      `No Fuss Needed`,
      `Living High is Not a Crime - Part 1`,
      `Living High is Not a Crime - Part 2`,
      `Harley Forever`,
      `Hot Delivery`,
      `Scavenger`,
      `Sales Night`,
      `The Blood of War - Part 3`,
      `The Stylish One`,
      `Supervisor`,
      `Textile - Part 1`,
      `Textile - Part 2`,
      `Long Line`,
      `Booze`,
    ],
    },
    {
      name: `Jaeger`,
      image: `https://assets.tarkov.dev/5c0647fdd443bc2504c2d371.webp`,
      quests: [
        `The Tarkov Shooter - Part 1`,
        `Acquaintance`,
        `The Survivalist Path - Thrifty`,
        `The Survivalist Path - Zhivchik`,
        `The Survivalist Path - Wounded Beast`,
        `The Survivalist Path - Tough Guy`,
        `The Survivalist Path - Cold Blooded`,
        `The Survivalist Path - Junkie`,
        `The Survivalist Path - Eagle-Owl`,
        `The Survivalist Path - Combat Medic`,
        `The Huntsman Path - Trophy`,
        `The Huntsman Path - Forest Cleaning`,
        `The Huntsman Path - Controller`,
        `The Huntsman Path - Justice`,
        `The Huntsman Path - Evil Watchman`,
        `Stray Dogs`,
        `The Huntsman Path - Outcasts`,
        `The Tarkov Shooter - Part 2`,
        `The Tarkov Shooter - Part 3`,
        `The Tarkov Shooter - Part 4`,
        `The Tarkov Shooter - Part 5`,
        `The Tarkov Shooter - Part 6`,
        `The Tarkov Shooter - Part 7`,
        `The Tarkov Shooter - Part 8`,
        `The Huntsman Path - Secured Perimeter`,
        `The Delicious Sausage`,
        `Cease Fire`,
        `The Huntsman Path - Factory Chief`,
        `The Huntsman Path - Woods Keeper`,
        `Courtesy Visit`,
        `Reserve`,
        `Shady Business`,
        `Broadcast - Part 3`,
        `Pest Control`,
        `The Huntsman Path - Eraser - Part 1`,
        `The Hermit`,
        `The Huntsman Path - Sadist`,
        `The Huntsman Path - Administrator`,
        `Ambulance`,
        `Broadcast - Part 4`,
        `Nostalgia`,
        `Fishing Place`,
        `Hunting Trip`,
        `The Huntsman Path - Eraser - Part 2`,
        `The Huntsman Path - Sellout`,
        `The Huntsman Path - Relentless`,
        `Hunter`,
        `Slaughterhouse`,
        `Swift One`,
      ],
    },
    {
      name: `Lightkeeper`,
      image: `https://assets.tarkov.dev/638f541a29ffd1183d187f57.webp`,
      quests: [
        `Information Source`,
        `Snatch`,
        `Missing Informant`,
        `Return the Favor`,
        `Payback`,
        `Provocation`,
        `Following the Bread Crumbs`,
        `Spotter`,
        `Make an Impression`,
        `Trouble in the Big City`,
      ],
    },
  ];
  await Trader.insertMany(traders);
  console.log(`Created traders!`);
};

const run = async () => {
  await main();
  db.close();
};

run();
